# Generated by Django 2.2.2 on 2019-07-24 15:49

import apps.resp_predefinida.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resp_predefinida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestapredefinida',
            name='id',
        ),
        migrations.RemoveField(
            model_name='respuestapredefinida',
            name='nombre',
        ),
        migrations.AddField(
            model_name='respuestapredefinida',
            name='codRespuestaP',
            field=models.CharField(default=apps.resp_predefinida.models.RespuestaPredefinida.codRespuestaP, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='respuestapredefinida',
            name='contUso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestapredefinida',
            name='descripcion',
            field=models.CharField(default='d', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestapredefinida',
            name='estatus',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
    ]
