# Generated by Django 2.2.2 on 2019-07-24 17:11

import apps.resp_predefinida.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resp_predefinida', '0002_auto_20190724_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestapredefinida',
            name='categoria',
            field=models.CharField(choices=[('pet', 'Petición'), ('que', 'Queja'), ('rec', 'Reclamo'), ('sug', 'Sugerencia')], default='PET', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuestapredefinida',
            name='codRespuestaP',
            field=models.CharField(default=apps.resp_predefinida.models.RespuestaPredefinida.codRespuestaP, max_length=8, primary_key=True, serialize=False),
        ),
    ]
