# Generated by Django 2.2.2 on 2019-07-24 17:34

import apps.resp_predefinida.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resp_predefinida', '0004_auto_20190724_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestapredefinida',
            name='codRespuestaP',
            field=models.CharField(default=apps.resp_predefinida.models.RespuestaPredefinida.codRespuestaP, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respuestapredefinida',
            name='contUso',
            field=models.IntegerField(default=0),
        ),
    ]
