# Generated by Django 2.2.2 on 2019-07-24 22:56

import apps.datos_externos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('codOficina', models.CharField(default=apps.datos_externos.models.Oficina.cod_Oficina, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(default='Barquisimeto', max_length=30)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datos_externos.Persona')),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
            bases=('datos_externos.persona',),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datos_externos.Persona')),
                ('cargo', models.CharField(choices=[('ger', 'Gerente'), ('admin', 'Administrador del Sistema'), ('gestorr', 'Gestor de reclamos'), ('gestorpqs', 'Gestor de PQS'), ('atencioncli', 'Atención al cliente'), ('tec', 'Técnico')], max_length=20)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('codOficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_externos.Oficina')),
            ],
            bases=('datos_externos.persona',),
        ),
    ]
