# Generated by Django 2.2.2 on 2019-07-27 01:57

import apps.datos_externos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_externos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codCiudad', models.CharField(default=apps.datos_externos.models.Ciudad.cod_Ciudad, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('nroContrato', models.AutoField(primary_key=True, serialize=False)),
                ('nroAsociado', models.CharField(max_length=10)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('codCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_externos.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codEstado', models.CharField(default=apps.datos_externos.models.Estado.cod_Estado, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codServicio', models.CharField(default=apps.datos_externos.models.Servicio.cod_Servicio, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=120)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('codZona', models.CharField(default=apps.datos_externos.models.Zona.cod_Zona, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('codCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_externos.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleContrato',
            fields=[
                ('codDetContrato', models.CharField(default=apps.datos_externos.models.DetalleContrato.cod_DetCont, max_length=8, primary_key=True, serialize=False)),
                ('codServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_externos.Servicio')),
                ('nroContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_externos.Contrato')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='codZona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_externos.Zona'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='codEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_externos.Estado'),
        ),
    ]
