# Generated by Django 2.2.2 on 2019-07-26 17:43

import apps.pqs.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PQS',
            fields=[
                ('codPQS', models.CharField(default=apps.pqs.models.PQS.cod_pqs, max_length=8, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('p', 'Peticion'), ('q', 'Queja'), ('s', 'Sugerencia')], max_length=1)),
                ('descripcion', models.CharField(max_length=500)),
                ('fechaRegistro', models.DateField(default=datetime.datetime.now)),
                ('fechaFinalizado', models.DateField()),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
