# Generated by Django 2.2.2 on 2019-07-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqs',
            name='fechaFinalizado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
