# Generated by Django 2.2.2 on 2019-07-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqs', '0002_auto_20190726_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqs',
            name='categoria',
            field=models.CharField(choices=[('P', 'Peticion'), ('Q', 'Queja'), ('S', 'Sugerencia')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pqs',
            name='estatus',
            field=models.CharField(choices=[('P', 'Pendiente'), ('M', 'Marcada'), ('A', 'Atendida')], default='P', max_length=1),
        ),
    ]
