# Generated by Django 2.2.3 on 2019-11-07 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqs', '0004_auto_20190726_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPQS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.CharField(max_length=200)),
                ('usuarioEncargado', models.CharField(max_length=20)),
                ('pqs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pqs.PQS')),
            ],
        ),
    ]
