# Generated by Django 2.2.3 on 2019-11-10 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pqs', '0005_historicopqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqs',
            name='responsablePQS',
            field=models.ManyToManyField(blank=True, related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicopqs',
            name='fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
