# Generated by Django 2.2.3 on 2019-11-10 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqs', '0006_auto_20191110_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqs',
            name='nombreUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
    ]
